import type { Metadata } from "next";
import "./globals.css";
import { Rethink_Sans } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rethinkSans = Rethink_Sans({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rethinkSans.className}>
      <body>{children}</body>
    </html>
  );
}
